### ISSUE TITLE
Thaumcraft bug with recipes

### ISSUE THREAD

**Issue by tupator4y** [SpeeeDCraft/TerraFirmaGreg-1.12.2#11]
Рецепты таумкрафта все сломанные
Не делаются доски из бревен серебрянного и великого дерева.
Рецепт глины в тигеле требует землю из обычного майна, земля tfc не подходит, как и все остальные предметы....
![2021-05-13_08 46 11](https://user-images.githubusercontent.com/65742863/118084042-a9e32980-b3c8-11eb-888e-059b2bc5b3f1.png)
![2021-05-13_08 47 55](https://user-images.githubusercontent.com/65742863/118084050-ae0f4700-b3c8-11eb-9f46-1f18ebf4356d.png)

**Comment by SpeeeDCraft** [comment]
Исправлены, начальные крафты, некоторых предметов, остальное по мере нахождения багов.
