### ISSUE TITLE
Фича для совместимости руд GregTech с механиками TFC

### ISSUE THREAD

**Issue by BayerHeroine** [SpeeeDCraft/TerraFirmaGreg-1.12.2#110]
Может добавить переработку греговских руд, приближенных по смыслу к ТФКшным. Вот мы добываем киркой блок греговской руды, и добавить крафт, блок этой руды с молотом обычным, и получится ТФКшная руда. Например, какой-нибудь блок руды Brown Limonite из гречки после обработки молотом, превращается в Poor/Normal/Rich Limonite Ore из ТФК, и т. д. То есть, ТФКшные куски руд просто станут промежуточным костылем для переработки на первичном этапе. Собственно, их можно спокойно плавить, не опасаясь за совместимость с гречкой.

**Comment by SpeeeDCraft** [comment]
Добавлено, но с некоторыми интересными изменениями и дополнениями, готовый вариант будет представлен в R3.3.0.
