### ISSUE TITLE
Ошибки перевода

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#118]
Прикрепляйте сюда ошибки и неточности перевода

**Comment by koliagas** [comment]
![image](https://user-images.githubusercontent.com/6399499/169521225-12364153-e2e8-407b-83b9-f35f8fbc14fd.png)

**Comment by koliagas** [comment]
![image](https://user-images.githubusercontent.com/6399499/169583947-d3d04765-f059-4d6a-ac0d-37de0acec3c6.png)
эатапах

**Comment by koliagas** [comment]
![image](https://user-images.githubusercontent.com/6399499/169590833-06706ea5-a5d6-4859-8706-787131783e54.png)
ловянные кабели

**Comment by koliagas** [comment]
![image](https://user-images.githubusercontent.com/6399499/169593267-b96feae4-4c54-4c0a-9e97-469ca37d561e.png)
уапряжения

**Comment by koliagas** [comment]
![image](https://user-images.githubusercontent.com/6399499/169667154-e23d9ca9-86c6-459c-971d-be95073e2c09.png)

**Comment by koliagas** [comment]
![image](https://user-images.githubusercontent.com/6399499/169669187-2d2e6fd7-eaf8-4b8e-8cc4-20ff4a48bf4d.png)
еальной жизни

**Comment by koliagas** [comment]
![image](https://user-images.githubusercontent.com/6399499/169669216-3f30e3c1-e418-4bb9-9a0c-ab68bcd660d1.png)
с пакетами непонятный перевод, я так понимаю, что там должны быть "Эти пакеты"

**Comment by Xikaro** [comment]
Уточни контекст, не вижу ошибки

**Comment by koliagas** [comment]
> Уточни контекст, не вижу ошибки

4 абзац, "Каждый тик..."  , второе предложение "Эти пакет имеют два параметра"

**Comment by koliagas** [comment]
![image](https://user-images.githubusercontent.com/6399499/169710510-92dc5af7-1674-4aad-b088-dee86b832f7e.png)
режим очистики

**Comment by koliagas** [comment]
![image](https://user-images.githubusercontent.com/6399499/170251130-067418f0-c73a-454b-a984-bd9c6f0d437a.png)
выходной люк переведен как входной

**Comment by Xikaro** [comment]
Исправлено, еще давай))

**Comment by koliagas** [comment]
> Исправлено, еще давай))

как найду, скину)

**Comment by koliagas** [comment]
![image](https://user-images.githubusercontent.com/6399499/170860921-5bc906aa-dd09-4971-8d14-a173f2ffbfbf.png)
Две Н (а я то думал, почему по поиску не бьется), кстати у остальных тоже одна вместо двух букв 'Н'

**Comment by koliagas** [comment]
![Screenshot_20220530_155332](https://user-images.githubusercontent.com/6399499/170996476-315bcfb0-886f-4a0a-b4bd-2dbac6e85f23.png)
Удучшенное

**Comment by koliagas** [comment]
![image](https://user-images.githubusercontent.com/6399499/170996611-beea3df6-d532-4f95-b205-ea16d240da25.png)

**Comment by koliagas** [comment]
![Screenshot_20220530_155418](https://user-images.githubusercontent.com/6399499/170996675-f89e177a-b228-4eee-8d00-4e25099d4882.png)

**Comment by koliagas** [comment]
![Screenshot_20220530_174255](https://user-images.githubusercontent.com/6399499/171015667-d088e592-e6c1-4458-b739-0bd8a13ba3cf.png)
УлучшеННый

**Comment by limka1200** [comment]
![image](https://user-images.githubusercontent.com/21083799/172039761-fdf60506-96da-4001-afad-dbc5bd27c0d9.png)
**Б**езопасной

**Comment by limka1200** [comment]
![image](https://user-images.githubusercontent.com/21083799/172040249-4181b651-61ac-4a2a-a115-b3695240de2c.png)
**т**олько

**Comment by limka1200** [comment]
![image](https://user-images.githubusercontent.com/21083799/173254596-2bf45ba8-3bde-40fa-ba6e-fde89631387e.png)
**о**тключены
![image](https://user-images.githubusercontent.com/21083799/173254667-9dcb6188-a8dd-421a-a3e0-50e5ce1d7493.png)
**Б**ОЛЬШОГО

**Comment by nemo48rus** [comment]
![image](https://user-images.githubusercontent.com/106464618/174140986-f0a77291-b7dd-45c9-858c-2902690de370.png)
Последние 2 абзаца. Format error и void энергии
Первое я подозреваю курсив "Примечание:" Энергия превышающая напряжение выходного люка будет уничтожена. 4A EV = IV = 8к.

**Comment by nemo48rus** [comment]
Во, вот это серьезное)) всех и правда в недоумение ставит, хоть и во всех клиентах так и есть. Изменить на оксид железа (III); триоксид железа; и прочие названия из Вики. Либо добавить более выгодный крафт в дуговой печи.
![unknown-10](https://user-images.githubusercontent.com/106464618/175811918-493c330d-8782-4103-a4c6-05e0195a4b1b.png)

![Screenshot_2022-06-26-14-27-56-391_com android chrome](https://user-images.githubusercontent.com/106464618/175811909-4e8d5d92-535f-41db-a990-d3be0efe6eed.jpg)

**Comment by SpeeeDCraft** [comment]
Это железо вообще, должно иметь название гематит, исправим в Некст патче.

**Comment by Xikaro** [comment]
Исправлено в dev
