### ISSUE TITLE
Не правильные пропорции создания крицы в горне

### ISSUE THREAD

**Issue by limka1200** [SpeeeDCraft/TerraFirmaGreg-1.12.2#119]
**Описание бага**
Из кусочков пыли не должен получатся слиток. Ну сами понимаете они 1/9 слитка. Но там и из 1/4 тоже самое. 
Вижу чисто всего напихали не вникая в пропорции.

**Как оно должно было работать?**
Думаю простое решение , цельную пыль лишь принимать в том рецепте. 

**Скриншоты**
![image](https://user-images.githubusercontent.com/21083799/169671643-2aa70cfe-9914-4168-baad-f47a6cc0b43e.png)
![image](https://user-images.githubusercontent.com/21083799/169671861-ed243e04-38d2-40b7-8a13-125ddd40396a.png)

**Модпак**
 - Версия TFG: 3.2.6 lite

**Comment by Xikaro** [comment]
это было сделано, из-за ошибки обработки машинами GT, предметов с юнитами металла, это было сообщено разработчикам, в обновлении 3.3.0, реализован обходной путь, все будет работать корректно и пропорционально
![Screenshot_36](https://user-images.githubusercontent.com/55663835/169672170-d1152557-076c-4a29-9916-d81262cfcfad.png)

**Comment by SpeeeDCraft** [comment]
Чисто напихали не вникая? Серьезно? Прежде чем такое писать вникни в суть дела, в HEI отображается просто какой металл можно переработать в крицу и не более. Если ты туда затолкал пыль, получишь 9 своих юнитов.
