### ISSUE TITLE
no textures firmalife

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#121]
<firmalife:bismuth_bronze_mallet_head>
![Screenshot_86](https://user-images.githubusercontent.com/55663835/170693261-caa90296-a496-4113-a063-8592c8680fa0.png)
![Screenshot_85](https://user-images.githubusercontent.com/55663835/170693263-a74048b3-484e-485e-bf08-4a68eb9be35c.png)

**Comment by SpeeeDCraft** [comment]
Fixed in the recent TFG-Mod patch.
