### ISSUE TITLE
Пыль железа имеет 100 ед вместо 144.

### ISSUE THREAD

**Issue by limka1200** [SpeeeDCraft/TerraFirmaGreg-1.12.2#123]
**Скриншоты**
![image](https://user-images.githubusercontent.com/21083799/170856965-5918de12-8d82-4a8a-9f44-636d9732d31d.png)

**Модпак**
 - Версия TFG: R3.3.0а, Lite

**Что либо дополнительное**
Баг не визуальный, проверил в горне.
Также интересно будут ли мелкие части пыли переведены в формат 144 ед? 
Например: маленькая кучка (1/4) 25ед в 144/4=36

**Comment by SpeeeDCraft** [comment]
На счет вопроса в конце, да, мы о них просто забыли чутка, спасибо за оповещение, исправим в следующем обновлении.

**Comment by SpeeeDCraft** [comment]
Исправлено
