### ISSUE TITLE
Не выгодный крафт пластин в кузнечном молоте

### ISSUE THREAD

**Issue by limka1200** [SpeeeDCraft/TerraFirmaGreg-1.12.2#125]
**Описание бага**
Из 3 слитков получается 2 пластины.

**Как оно должно было работать?**
Читал предыдущие обновления что был изменен крафт из двойного слитка к пластине в 1 слиток к 1 пластине.
На тот момент до изменения данный крафт был выгоден. Сейчас думаю решением 1 к 1 сделать.
upd: и описание квеста обновите, если поправите крафт.

**Скриншоты**
![image](https://user-images.githubusercontent.com/21083799/170863004-26c5a8cb-a29e-4505-9e7a-6f8d897f62b0.png)
![image](https://user-images.githubusercontent.com/21083799/170863661-840a948c-2e95-40db-a6a8-265e129938ba.png)

**Модпак**
 - Версия TFG R3.3.0а, Lite
 
 Еще вопрос: этот бонус только для кузнечного молота не высокого давления?
 а то мне наковальня не вернулась при крафте парового кузнечного молота высокого давления.

**Comment by SpeeeDCraft** [comment]
Квест поправили, то что ты не получил наковальню все правильно, просто немного ошиблись в квесте.
И исправили рецепт в Forge Hammer, чтобы рецепт был не бесполезен.

**Comment by SpeeeDCraft** [comment]
Было принято решение оставить все как есть в Forge Hammer, так как это первая машинка которая позволяет не ковать в ручную и у нее будут потери, если хочется избежать потерь нужно будет сделать Bender(LV).
