### ISSUE TITLE
Баг пластин в AE.

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#127]
**Описание бага**
Багается крафт/отображение пластин в терминале AE.

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**
1. Автоматизировать гибочный станок (от места, от уровня - не зависит)
Не связано с новым аддоном на АЕ (разные пробовались интерфейсы).
2. Забить рецепт трубы с инструментами (ore-dictonary включён) через молекулярный сборщик.
3. Заказать: стальную, бронзовую (из трёх пластин) трубу, заказать логический процессор из АЕ (все крафты, где нужны золотые пластины).

По факту при моделировании (не проходит) просчёт не берётся с учётом склада. Работает всё, кроме пластин.
**Как оно должно было работать?**
Не багаться.

**Скриншоты**
![image](https://user-images.githubusercontent.com/106464618/171227309-78a5f058-1243-470e-a199-8d2fd11120e3.png)
![image](https://user-images.githubusercontent.com/106464618/171225398-f0024078-853f-49ac-8d50-92ab2e014bda.png)

**Модпак**
 TFG Lite 3.3.0a

**Что либо дополнительное**
Добавьте сюда любой другой контекст, касающийся этой проблемы.

**Comment by Xikaro** [comment]
При моделировании ситуации, крафт труб прошел успешно, ошибка при моделировании рецепта на логический процессор ае, в ходе проверки, создал два шаблона для труб, с замещением по ордикту и нет, результат, по ордикту шаблон видит листы золота в хранилище, без, соответственно нет. Это не работает, так как у некоторых пластин есть юниты металла тфк, которые мешают нормально определить машине что это за предмет, крафты без замещения, работают, если там нет юнитов металла(проверил на трубах из наквада). Решение: при не жидкостных крафтах, использовать замещение, по поводу жидкостных рецептов, я напишу на гит разработчику аддона на жидкостные крафты, для добавления функции замещения, в шаблоны, с использованием жидкости. Здесь тикет закрываю.
