### ISSUE TITLE
Missing Tanned Leather recipe

### ISSUE THREAD

**Issue by AtelierAmber** [SpeeeDCraft/TerraFirmaGreg-1.12.2#129]
**Describe the bug**
Bound Leather can't be used in the campfire or forge anymore so it's impossible to get Tanned Leather

**DeepL translation** 
Связанная кожа больше не может быть использована в костре или кузне, поэтому невозможно получить дубленую кожу.

**Modpack**
 - TFG Huge R3.3.0 -

**Comment by Xikaro** [comment]
we know about the error, fixed in the update
