### ISSUE TITLE
Кодирует максимум 9 предметов расш. жидкостный терминал. Остальные срезает.

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#132]
**Описание бага**
Исчезает крафт и записывается неверная инфа в шаблон.

**Как воспроизвести?**
Жидкостный расширенный кодировщик работает некорректно:
срезает часть предметов из крафта.

**Скриншоты**
![image](https://user-images.githubusercontent.com/106464618/172021106-5a26ba7f-7d5f-4b8c-a3a2-6ecc96714bf5.png)
![image](https://user-images.githubusercontent.com/106464618/172021116-8f01928c-7f45-4cdd-92c1-a93d49ee251a.png)

**Модпак**
 TFG 3.3.0a
 AE2 Fluid Crafting

**Comment by Xikaro** [comment]
Исправлено в новой версии мода, в обновлении модпака пофиксится
