### ISSUE TITLE
Double plates aren't forgable

### ISSUE THREAD

**Issue by AtelierAmber** [SpeeeDCraft/TerraFirmaGreg-1.12.2#133]
**Describe the bug**
Double wrought iron plates can't be forged in the anvil, making the Tuyere impossible to make. They also can't be heated in the forge. This also exists for all the double bronze plates, double copper plate, etc. Basically all the double plates can't be used in the forge or the anvil. This also means all the metal armor is uncraftable as well.

![image](https://user-images.githubusercontent.com/22966571/172030597-a55ebf27-e915-4fd5-a23a-4df8391ee327.png)

**Comment by SpeeeDCraft** [comment]
Already fixed in dev
