### ISSUE TITLE
Dupe bug: Crafting the Empty Fluid Bowl doesn't consume the Ceramic Pot

### ISSUE THREAD

**Issue by AtelierAmber** [SpeeeDCraft/TerraFirmaGreg-1.12.2#134]
**Describe the bug**
Crafting the Empty Fluid Bowl doesn't consume the Ceramic Pot.

![image](https://user-images.githubusercontent.com/22966571/172030760-e7fbc151-a86f-48f6-b541-89d1af8066df.png)

![image](https://user-images.githubusercontent.com/22966571/172030767-9919548a-77cb-4930-afb6-53a453174638.png)

**Comment by SpeeeDCraft** [comment]
I can't repeat it, can you attach a video?

**Comment by SpeeeDCraft** [comment]
I've already checked twice, I can't confirm the bug, I'm closing it.
