### ISSUE TITLE
GregTech Primitive Blast Furnace Controller is uncraftable

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#135]
**Describe the bug**
The GregTech Primitive Blast Furnace Multiblock Controller cannot be crafted, but it's other material (firebricks) can be crafted.

**To Reproduce**
1. Attempt to fetch the JEI recipe for the Primitive Blast Furnace Multiblock.

**Expected behavior**
Expected behavior would either be that these recipes are entirely unobtainable, or, the blast furnace control block would have a recipe (likely of similar cost to the TFC blast furnace (maybe with steel?), as a clay-intensive alternative for making bulk/cheaper steel and black steel). 

**Screenshots**
Screenshot of the mutliblock viewer;
![image](https://user-images.githubusercontent.com/32183732/172030954-45e18af0-1303-48e9-b437-af4a84311d93.png)
Screenshot of the firebricks recipe (I suggest a different name for disambiguation. Maybe Clad Furnace Bricks?)
![image](https://user-images.githubusercontent.com/32183732/172030964-d2eabdc4-d4e5-448f-a740-e4725aa0ee12.png)

**Modpack**
 R3.3.0, Huge.

**Comment by SpeeeDCraft** [comment]
Everything works correctly here, the bricks are needed for another multiblock or for decorative purposes.
