### ISSUE TITLE
Corail Tombstone Recipes are visible, but all features other than player graves are disabled

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#139]
**Describe the bug**
Corail Tombstone recipes for magical tombs, the book of disenchanting, etc, are visible in JEI when they are unobtainable in-game.

**To Reproduce**
1. Search @corail in JEI.

**Expected behavior**
These items, under expected behavior, would either be implemented into the lite/huge pack progression, or be hidden entirely.

**Screenshots**
Below is a screenshot of a corail tombstone item visible via JEI.
![image](https://user-images.githubusercontent.com/32183732/172031410-e6ecce0a-4980-48b1-a327-53fdbf677337.png)

**Modpack**
 - TFG R3.3.0, Huge

**Comment by SpeeeDCraft** [comment]
Fix: Just hide items from this mod.
