### ISSUE TITLE
GregTech full iron dusts have no crucible/bloomery recipes

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#141]
**Describe the bug**
Several fully compressed GT iron dusts (in this case magnetite) cannot be processed by the crucible or bloomery, while small piles of dust, and the raw ore can be.

**To Reproduce**
1. Attempt to insert fully compressed dusts into the bloomery or crucible GUI,
2. Watch items not be accepted by either multiblock.

**Expected behavior**
The expected behavior would be that all iron dust size variants can be processed by the bloomery/blastfurnace/crucible, or some combination thereof, with consistency. Currently it's a gamble what versions of certain iron ores can be processed by what early game metalworking multiblocks.

**Screenshots**
Below is a screenshot of the JEI tabs for magnetite ore, which has all TFC metal processing categories.
![image](https://user-images.githubusercontent.com/32183732/172031625-f2b8018b-c5ef-4115-9269-04a4f8e09c48.png)

Below is a screenshot of the JEI tabs for small magnetite dust, which has some TFC metal processing (lacks crucible),
![image](https://user-images.githubusercontent.com/32183732/172031610-ca8899eb-59e3-4aa4-be6d-3258caaeeaa1.png)

Below is a screenshot of the JEI tabs for full magnetite dust, which lacks any TFC metal processing.
![image](https://user-images.githubusercontent.com/32183732/172031596-259e8222-545c-43bf-876e-344c0be882e7.png)

**Modpack**
 - TFG R3.3.0, Huge.

**Comment by SpeeeDCraft** [comment]
Some dusts cannot be processed into TFC metal because they will no longer be processed in GT machines, because of this, what you described in the ticket happened, GTCEu will soon be updated in which a bug with recipes will be fixed and then what is described in this ticket will also be corrected.

**Comment by SpeeeDCraft** [comment]
Ждем, ждем, это исправит: https://github.com/GregTechCEu/GregTech/pull/666

**Comment by SpeeeDCraft** [comment]
Исправлено в следующем обновлении.
