### ISSUE TITLE
Missing texture in Firmalife greenhouse

### ISSUE THREAD

**Issue by AtelierAmber** [SpeeeDCraft/TerraFirmaGreg-1.12.2#143]
**Describe the bug**
Probably something on the Firmalife dev's end but thought I'd mention it. I've only tried with the Coffea seeds but this likely happens with other seeds as well.

![image](https://user-images.githubusercontent.com/22966571/172037706-11c8e447-6094-49a5-a105-fc6e5b5698fd.png)

**Comment by SpeeeDCraft** [comment]
duplicate #97
