### ISSUE TITLE
tfc_ph_compat seeds don't work in the greenhouse

### ISSUE THREAD

**Issue by AtelierAmber** [SpeeeDCraft/TerraFirmaGreg-1.12.2#145]
**Describe the bug**
Seeds from the Pams Harvestcraft TFC compat mod don't get planted in the greenhouse planters. Almost all other seeds work though, except for some having missing stage textures.

https://user-images.githubusercontent.com/22966571/172070202-5a6a2639-5d79-425e-bf42-6b763dc22396.mp4

**Modpack**
 - Modpack TFG Huge 3.3.0

**Comment by SpeeeDCraft** [comment]
The mod will be removed and replaced with GTFO.
