### ISSUE TITLE
GregTech Extractor uses Vanilla Seeds for Seedoil

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#146]
**Describe the bug**
The GregTech Extractor recipes for seedoil only use minecraft versions of seeds, and no TFC variants.

**To Reproduce**
1. Observe that the extractor's seedoil recipes do not include TFC seeds (oredict listallseed, which currently excludes many tfc florae seeds). 

**Expected behavior**
The expected behavior for this recipe would either be equal oil yields for all seeds, or, varying yields depending on plant species (perhaps to incentivize growing otherwise low priority types of plants, like weld/woah/indego).

**Screenshots**
Below is a screenshot of the extractor machine categories' JEI for seed oil.
![image](https://user-images.githubusercontent.com/32183732/172070254-367299d0-a74d-4115-ba04-ba9e761d28bb.png)

**Modpack**
 - TFG R3.3.0, Huge

**Comment by SpeeeDCraft** [comment]
Fixed in dev
