### ISSUE TITLE
PamsHarvestCraft Seed Gel excludes TFC Florae Seeds

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#147]
**Describe the bug**
The PamsHarvestCraft Seed Gel recipe excludes TFC Florae Seeds, which currently are much more common in the pack. This also appears to be the case with firmalife seeds (IE, pumpkins). 

**To Reproduce**
1. Attempt to craft seed gel with non-compat listed seeds,
2. Observe the invalid crafting table recipe.

**Expected behavior**
Expected behavior would be that all seeds are grouped together into one list, save for edge cases (like mushroom spores), and are valid for this recipe. A mixer/assembler recipe that uses seed oil later in the game would also be interesting to see. 

**Screenshots**
Below is a screenshot of the seed gel recipe in JEI, as well as the oredict used.
![image](https://user-images.githubusercontent.com/32183732/172070421-1696b8d5-7986-45e1-a3c3-d04fcb9e8f72.png)

**Modpack**
 - TFG R 3.3.0, Huge.

**Comment by SpeeeDCraft** [comment]
The mod will be removed and replaced with GTFO.
