### ISSUE TITLE
Невозможно создать питательную среду

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#148]
**Описание бага**
Невозможно создать питательную среду -> нет доступного Крафта мясного фарша.

Раз фирмалайф совсем не дружит с Грегом, то нужен костыль: к примеру подать ресурсы в молекулярный сборщик и нарисовать предмет, который будет использоваться для создания питательной среды.

**Comment by SpeeeDCraft** [comment]
![image](https://user-images.githubusercontent.com/52341158/172092347-c2233784-12f2-49dc-87d0-f9b53ce9c1a5.png)

Рецепт есть, но он не работает из-за бага GTCEu, разрабы уже работают над исправлением.
