### ISSUE TITLE
Double Ingot Recipe Removed

### ISSUE THREAD

**Issue by kslucashr** [SpeeeDCraft/TerraFirmaGreg-1.12.2#150]
Some Anvil and weld recipes seems to get removed in the last update, idk if this was intentional, i believe some was that was from tfctechmod but in the meanwhile some major recipes like all double ingot got removed too
The Version of the modpack that this happened is 3.3.2 lite
Im gonna put some screenshot of the log showing what recipes are removed

![unknown2](https://user-images.githubusercontent.com/90533231/172504106-7b884b36-7639-4916-804a-28a92a3815fc.png)
![unknown](https://user-images.githubusercontent.com/90533231/172504107-784345b8-4837-4ff1-890f-df4a79dca70c.png)

**Comment by SpeeeDCraft** [comment]
I don't understand why this happened, but I fixed it.
