### ISSUE TITLE
[Several] Various 'uses vanilla materials' oversights

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#151]
**Describe the bug(s)**
The following items still use vanilla materials:
- Gregtech Wooden Crates (vanilla iron screws),
![image](https://user-images.githubusercontent.com/32183732/172506677-32ec52b3-1575-49be-a92a-8c35637ba57d.png)
- Thaumic Periphery Pauldron (vanilla iron and vanilla iron plates),
![image](https://user-images.githubusercontent.com/32183732/172506793-d35a277b-7726-4180-a970-856a0528a62e.png)
- Thuamic Bases Tobacco Seeds (uses vanilla minecraft seeds, likely requires vanilla tilled soil), 
![image](https://user-images.githubusercontent.com/32183732/172506933-c0366106-d6e6-41cb-8492-9d9771aae95c.png)
- Thaumic Bases Trees (all require vanilla oak saplings), below is an example of one of the 3 infusion recipes (golden oak),
![image](https://user-images.githubusercontent.com/32183732/172507057-c2a4bfcb-541b-408b-9ae8-ead24c5fbb1e.png)
- Thaumic Bases Thaumaturge's Campfire (requires vanilla cobblestone and gravel)
![image](https://user-images.githubusercontent.com/32183732/172507308-d1250fb1-dd5c-4cb4-9c93-fc2555f22ab9.png)
 
**Modpack**
 - TFG-NH R 3.3.2, Huge

**Comment by SpeeeDCraft** [comment]
The recipes of thaumcraft and its addons have not changed much, you don't have to write about them, we will have a separate update to fix all the shit from thaumcraft, now we have a different development priority, but I can assume that this will happen somewhere after R3.5.

**Comment by SpeeeDCraft** [comment]
**Gregtech Wooden Crates (vanilla iron screws),** <- This recipe is fixed in dev

**Comment by FDAapproved** [comment]
For future reference, are bulk threads like this alright? I didn't want to pollute your issue tracker with 50 of these at once.

**Comment by SpeeeDCraft** [comment]
At the expense of problems with Thaumcraft and its addons, you can attach here. You can create new tickets for any other problems.

**Comment by FDAapproved** [comment]
Some new reports, since this thread is a nice spot for them:
- Vanilla: Hoppers still use vanilla iron gears and plates,
![image](https://user-images.githubusercontent.com/32183732/172704783-beab5a28-7391-40aa-a228-9a21163de921.png)
- GalaxySpace: The grapple still uses vanilla iron ingots,
![image](https://user-images.githubusercontent.com/32183732/172704863-3ad8bebc-f05a-442e-8266-c07d11ea9061.png)

**Comment by SpeeeDCraft** [comment]
After the patch, all items that use iron for crafting will automatically accept wrought iron.

**Comment by SpeeeDCraft** [comment]
Fixed in dev
