### ISSUE TITLE
GregTech Gemstone File recipes still use tools instead of percision laser

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#152]
**Describe the bug**
Below is a screenshot of one of the recipe(s) in question. File recipes still appear to be generated for every applicable gemstone type. 
![image](https://user-images.githubusercontent.com/32183732/172507681-f5116e70-48f2-4283-95f5-ee39684660f8.png)

**Modpack**
 - TFG-NH, R 3.3.2, Huge

**Comment by SpeeeDCraft** [comment]
Fixed in dev
