### ISSUE TITLE
FirmaLife Salt Buckets can stack; breaks crafting recipe if done in batches (via shift + click)

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#153]
**Describe the bug**
When trying to batch-craft the stackable 'bucket with salt' items recently added, only one wooden bucket and set of salt piles is returned, with the rest of the buckets and salt being deleted.

**To Reproduce**
1. stack more than one salt bucket, move said salt bucket into the 2 x 2 crafting grid;
2. shift+click to process the entire batch,
3. watch as any buckets past the first are deleted from your inventory.

**Expected behavior**
The expected behavior in this case would be that salt-buckets are unstackable, preventing this issue entirely by forcing them to be crafted back into buckets and salt one at a time.

**Modpack**
 - TFG-NH, R3.3.3, Huge.

**Comment by SpeeeDCraft** [comment]
Fixed in dev
