### ISSUE TITLE
Пропажа века! МЭ карточки пропадают!

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#154]
**Описание бага**
Уничтожение карт МЭ при вкладывании в сетевой инструмент к уже имеющимся карточкам. При этом если кинуть в свободный слот, то всё работает корректно.
AE cards delete when you "stack" them into web tool from mod.

**Скриншоты**
![2022-06-09_18-06-37](https://user-images.githubusercontent.com/106464618/172891274-b686b45f-e412-403d-92e7-40ea12571367.png)
![2022-06-09_18-06-48](https://user-images.githubusercontent.com/106464618/172891268-1cc37e3f-2062-46bf-9155-d6667ad0085c.png)
![2022-06-09_18-07-11](https://user-images.githubusercontent.com/106464618/172891256-badcb907-24fc-4031-81c9-3ccc2d79816c.png)

**Модпак**
 - Версия TFG(3,3,4)

**Comment by Xikaro** [comment]
Не смог воспроизвести, возможно в одном из обновлений  AE, исправлено

**Comment by nemo48rus** [comment]
![image](https://user-images.githubusercontent.com/106464618/174426801-40223ae0-e722-4688-8b46-d8742abf5f79.png)
![image](https://user-images.githubusercontent.com/106464618/174426818-5ad698ce-1b0e-4581-bfc3-88768b37c537.png)
![image](https://user-images.githubusercontent.com/106464618/174426841-7e6a3d3c-6c01-454f-9b35-5995766b252d.png)
![image](https://user-images.githubusercontent.com/106464618/174426857-aa915934-17df-4b5c-aba8-b9033cb48569.png)
![image](https://user-images.githubusercontent.com/106464618/174426884-3d47316b-0ea2-4bef-890d-fc644a93123b.png)

**Comment by Xikaro** [comment]
Проверял на серве?

**Comment by nemo48rus** [comment]
Я записал на серве))

сб, 18 июн. 2022 г., 10:06 Xikaro ***@***.***>:

**Comment by Xikaro** [comment]
Проверь в сингле

**Comment by Xikaro** [comment]
шина экспорта с картой нечеткости, не правильно работает с дробленными пыльками GT

**Comment by Xikaro** [comment]
https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/123
