### ISSUE TITLE
Missing loading screen texture

### ISSUE THREAD

**Issue by AtelierAmber** [SpeeeDCraft/TerraFirmaGreg-1.12.2#156]
**Describe the bug**
Missing loading screen texture

![image](https://user-images.githubusercontent.com/22966571/172965575-36e24f4e-a752-4d3d-89a6-111d4a59c68c.png)

**Modpack**
 - Modpack TFG Huge 3.3.3

**Comment by Xikaro** [comment]
Is it the same on 3.3.4?

**Comment by AtelierAmber** [comment]
Not sure, just loaded 3.3.4 and didn't see it but if the screens are random it could still occur.

**Comment by Xikaro** [comment]
I'll check it out

**Comment by SpeeeDCraft** [comment]
Fixed in dev
