### ISSUE TITLE
Brass sleeve recipe not working

### ISSUE THREAD

**Issue by AtelierAmber** [SpeeeDCraft/TerraFirmaGreg-1.12.2#158]
**Describe the bug**
Brass sleeve recipe doesn't work. This is on a server as well if it's a server issue. This also happens with the rackwheel pieces.

![image](https://user-images.githubusercontent.com/22966571/173194861-69e92676-9e79-4ec9-90fb-5a9494b19f72.png)

![image](https://user-images.githubusercontent.com/22966571/173194864-b5110691-c6f2-4be7-858e-58d56724c3a4.png)

**Modpack**
 - Modpack TFG Huge 3.3.3: -

**Comment by SpeeeDCraft** [comment]
Fixed in dev
