### ISSUE TITLE
Рецепт кованного железа из незаконченного слитка в кузнечном молоте не работает

### ISSUE THREAD

**Issue by limka1200** [SpeeeDCraft/TerraFirmaGreg-1.12.2#159]
**Описание бага**
Проверял Кузнечный молот с другими рецептами все работало, пар есть, выход для пара не загражден.
![image](https://user-images.githubusercontent.com/21083799/173254157-1f448c3e-47cd-41f9-a287-b61257d4d4fa.png)
v3.3.4 lite

Также предлагаю добавить рецепт из очищенной крицы в незаконченный слиток в кузнечный молот.
Если возможно, то и из крицы в очищенную крицу.

**Comment by SpeeeDCraft** [comment]
Проблема классного мода под названием GTCEu. Ждём фикса, который скоро закончат.

**Comment by nemo48rus** [comment]
*Заставка из спанча*
2 months later...

**Comment by SpeeeDCraft** [comment]
Ждем, ждем, это исправит: https://github.com/GregTechCEu/GregTech/pull/666

**Comment by SpeeeDCraft** [comment]
Исправлено в следующем обновлении.
