### ISSUE TITLE
Suggestion: Computercraft (CC Tweaked) Integration for Lite and Huge

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#160]
**Describe the solution you'd like**
I think it would be very interesting to see a Computer-Craft styled addon wrapped into the pack for lategame automation, with how powerful the mod and it's associated addons can be. 

**Suggested Addon Links:**
- https://www.curseforge.com/minecraft/mc-mods/cc-tweaked
- https://www.curseforge.com/minecraft/mc-mods/plethora-peripherals

**Describe alternatives you've considered**
Mods like AE2 and project red redstone already allow for bitwise computing, though interfacing via an actual coding language would probably be more intuitive for most players, in this regard.

**Additional context**
The main thing I'm unsure of is where Computercraft would actually lie in progression for the modpack; nor how well it interfaces with GregTech/misc mod multiblocks. Plethora Peripherals seems to be a universal wrapper of sorts that allows computer craft to read arbitrary metadata, so that may be a good option in lieu of 10+ addons, like thaumcraft has.

**Comment by Xikaro** [comment]
Later, a mod will be added and possibly add-ons to it, open computers
It's already planned

**Comment by FDAapproved** [comment]
Nice! I had no idea; glad we're on the same page in that case.
