### ISSUE TITLE
Квесты

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#162]
т.к. заменён греговский вариант.
![image](https://user-images.githubusercontent.com/106464618/174037998-171acc78-b10f-41be-adcb-c025f5599788.png)
![image](https://user-images.githubusercontent.com/106464618/174038448-61c92dc5-3d79-46fd-963c-5490d8dc92ef.png)

**Comment by nemo48rus** [comment]
![image](https://user-images.githubusercontent.com/106464618/174048985-8be221f8-7d59-4069-9c85-986e6f775299.png)
Портативный сканер в ту же тележку
Стоит невозможный крафт с LV батарейкой

**Comment by SpeeeDCraft** [comment]
Квест исправили

**Comment by nemo48rus** [comment]
![image](https://user-images.githubusercontent.com/106464618/174271472-17d3537d-3c6b-4db4-b1ac-d024bb5fd8b9.png)
Ещё один 🗡️

**Comment by Xikaro** [comment]
Поправил

**Comment by nemo48rus** [comment]
![image](https://user-images.githubusercontent.com/106464618/174275978-aa7898e5-7889-4e27-9e39-399e0ff053be.png)
В квесты ракеты принимаются только без хранилищ. (кроме второй)

**Comment by nemo48rus** [comment]
![image](https://user-images.githubusercontent.com/106464618/174286894-70d12999-3645-4d84-affc-a8829e2c87c7.png)
Кластер лапотронных энергетических шаров приобретают NBT и имеющиеся не засчитывают.

**Comment by nemo48rus** [comment]
![image](https://user-images.githubusercontent.com/106464618/174289799-c221ff88-c768-4917-811d-2a2baba921a7.png)
После выполнения квеста засасывается жидкость и выплёвывает пустую капсулу, хотя по квесту оно должно возвращаться.
![image](https://user-images.githubusercontent.com/106464618/174289942-081e92f6-2e36-456e-aad1-3f962c30630b.png)

**Comment by Xikaro** [comment]
Исправлено в dev
