### ISSUE TITLE
Не отображаются расширенные интерфейсы

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#163]
**Описание бага**
Не отображаются расширенные интерфейсы в окне беспроводного терминала интерфейсов
Extended interfaces are not displayed in the wireless interface terminal window

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**
1.Craft Universal Terminal
2.Swap to Wireless Interface Terminal

**Как оно должно было работать?**
Что должно было произойти?

**Скриншоты**
![image](https://user-images.githubusercontent.com/106464618/174137214-faa9abc4-f86c-4035-b052-637309f7a420.png)
![image](https://user-images.githubusercontent.com/106464618/174138417-e469150a-a40e-48aa-b9bf-5db5037c90db.png)

**Модпак**
 - Версия TFG 3.3.4
 - AE2 Wireless Terminals (AE2wTLib) 1.12.2-1.0.34

**Comment by Xikaro** [comment]
Что тут?

**Comment by nemo48rus** [comment]
> Что тут?

Я снова Shift + Enter нажал. Щас заполню по форме ru/eng

**Comment by nemo48rus** [comment]
![image](https://user-images.githubusercontent.com/106464618/174280002-3b3c7a08-d939-4121-aa6a-6e8f3b4501b1.png)
Некорректная работа МЭ с греговскими инструментами. Крафтил 4 буровых II.
Получается он её не обрабатывает обратно, когда крафтит.

**Comment by Xikaro** [comment]
Окей, пусть все тут будет
Поясни еще, ты имеешь ввиду то, что инструменты  ме не забирает обратно?

**Comment by nemo48rus** [comment]
Нет, я нашёл отвёртку и забрал её к себе в сумку. Получается он не обрабатывает прочность электроотвёртки.

**Comment by nemo48rus** [comment]
![image](https://user-images.githubusercontent.com/106464618/174689658-02c32551-7472-4d63-b4f5-30b80fe48fad.png)
"Not a TFG Problem"
Крафт UHV 16A входного люка состоит из себя же. Должен быть UHV 4A сообразно остальным рецептам.

**Comment by Xikaro** [comment]
Ошибка с отображение расширенного интерфейса не будет устранена, так как автор мода WCT уже не будет выпускать обновление для 1.12

**Comment by nemo48rus** [comment]
>
>  Ну и шут тогда с ним: я уже приспособился расширять и перекладывать.
>
Будем надеяться что на других версиях учтёт недочёт и кто-то доработает на
этой. Но багрепорты будут время от времени прилетать)

Когда новая серия?))

**Comment by Xikaro** [comment]
https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/122
 запрос создан, на исправление ошибки, так же со своей стороны попытаюсь перенести крафты в сборщик, без использования инструментов, соответствен
