### ISSUE TITLE
Make coke burn brilliant white for blast furnace

### ISSUE THREAD

**Issue by AtelierAmber** [SpeeeDCraft/TerraFirmaGreg-1.12.2#164]
**Describe the solution you'd like**
The steel, black steel, red steel, and blue steel grind during the LV age gets tiresome due to having to micromanage the blast furnace. Coke is mentioned as a better alternative to coal and charcoal but apart from burning longer than those it has no use. In normal gregtech you use it with iron to make steel with less coal; I think it would be a good alternative to make it burn brilliant white in this so you use less coal and don't have to micromanage at all. You can just leave the blast furnace full of coke and it will make pig iron without any intervention or bellows.

**Comment by SpeeeDCraft** [comment]
Well, we did it, only now it is impossible to use coke for the furnace of a **forge**, coke can now be used only for a **blast furnace**.
