### ISSUE TITLE
Очищенная крица в тигеле

### ISSUE THREAD

**Issue by evg-95** [SpeeeDCraft/TerraFirmaGreg-1.12.2#165]
При плавке в тигеле куска очищенной крицы больше чем на 144 ед. , получается ровно 144 ед. кованного  железа.
Если использовать несколько кусков по 144 ед. всё работает нормально.

1) Положить в тигель кусок очиценной крицы  больше чем на 144 ед. , например на 576 ед.
2) Довести тигель до точки плавления крицы
3) Увидеть что кусок расправился в 144 ед. кованного  железа.

 - Версия TFG R3.3.4, Lite

**Comment by Xikaro** [comment]
It needs to be divided on an anvil, by 144
