### ISSUE TITLE
Conflicting recipes

### ISSUE THREAD

**Issue by AtelierAmber** [SpeeeDCraft/TerraFirmaGreg-1.12.2#169]
**Describe the bug**
Trying to craft gravel into flint with the forge hammer will instead craft sand due to a recipe conflict

**Screenshots**
![image](https://user-images.githubusercontent.com/22966571/174671809-191972b9-e64a-4e98-a41a-0b47a80c33be.png)

**Modpack**
 - Modpack TFG Huge 3.3.5: -

**Comment by SpeeeDCraft** [comment]
Fixed in dev
