### ISSUE TITLE
Minecraft Wooden Signs cannot be crafted with TFC woods (by hand)

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#171]
**Describe the bug**
Wooden Signs currently can only be hand-crafted with space-wood from 22-b, and otherwise require a gregtech assembler to be crafted (this was not the case in previous versions of the pack).

**Screenshots**
Below is a screenshot of the HEI entries for wooden sign recipes (only 2 pages, all kepler woods).
![image](https://user-images.githubusercontent.com/32183732/174689977-6987b85b-a240-46d4-9f59-e6422113b176.png)

**Modpack**
 - TFG-NH R3.3.5b, Huge

**Comment by SpeeeDCraft** [comment]
Fixed in dev
