### ISSUE TITLE
Нет использования для аргоновой плазмы в турбине. Logic?!

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#172]
**Скриншоты**
![image](https://user-images.githubusercontent.com/106464618/174850241-0c5d6306-4b4e-40d6-8713-bbe8e65a093f.png)

**Comment by Xikaro** [comment]
Это задел на будущее, много контента, который ПОКА не используется, не забывай, мод в бете еще, и так же ожидается аддоны
