### ISSUE TITLE
Incorrect quest description

### ISSUE THREAD

**Issue by AtelierAmber** [SpeeeDCraft/TerraFirmaGreg-1.12.2#173]
**Describe the bug**
Under the MV age quest line, the Oilsands quests says that you electrolyze the dust to get oil, but the actual recipe is to centrifuge the dust to get oil.
![image](https://user-images.githubusercontent.com/22966571/174917558-f4fc6e9c-37f3-418d-aa06-6f5435ac2c47.png)
![image](https://user-images.githubusercontent.com/22966571/174917571-4e9828a6-efaa-4045-a9ed-8e8e5cc6c142.png)

**Modpack**
 - Modpack TFG Huge 3.3.5: -

**Comment by Xikaro** [comment]
ok, I'll change, the recipe apparently changed with the update of the mod

**Comment by Xikaro** [comment]
fixed in dev
