### ISSUE TITLE
TFC Florae leather bags don't save nbt data (deletes items)

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#174]
**Describe the bug**
TFC Florae's leather bags will reset their nbt data when moved to a different inventory slot, voiding anything inside of them.

**To Reproduce**
1. Open a TFC Florae leather bag (right click in main hand),
2. Insert item(s) into the bag and close the bag's inventory menu,
3. Move the bag to another inventory slot, then back to it's original slot,
4. Open the bag again, and observe that it's now empty.

**Modpack**
 - Modpack TFG-NH R3.3.5b, Huge

**Comment by SpeeeDCraft** [comment]
The mod developer is a bad person, he said that nothing will be fixed on 1.12.2 anymore, so just don't use them. I hid them and deleted the recipes. Such things.
