### ISSUE TITLE
Terrafirmacraft iron grill has misaligned gui

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#175]
**Describe the bug**
The terrafirmacraft iron grill's backing image is misaligned with the actual inventory spaces, making navigating the menu without shift clicking fumbling in the dark.

**Expected behavior**
Ideally, the offset this menu uses would be corrected to align it with the actual gui object's screen positions, if possible. 

**Screenshots**
Below is a screenshot of the iron grill gui in it's current state (entire inventory is shifted one row up (the image being shifted one row down)).
![image](https://user-images.githubusercontent.com/32183732/175612732-e080e45a-7e6a-475c-9492-5a77aa2a6a98.png)

**Modpack**
 - TFG-NH R3.3.5b, Huge

**Comment by Xikaro** [comment]
I will correct

**Comment by Xikaro** [comment]
fixed in dev
