### ISSUE TITLE
Cellars Addon recipes only accept vanilla minecraft clay

### ISSUE THREAD

**Issue by FDAapproved** [SpeeeDCraft/TerraFirmaGreg-1.12.2#176]
**Describe the bug**
Cellars Addon recipes currently ignore TFC Florae clay variants (stoneware, etc). 

**Expected behavior**
Ideally these recipes would use a group oredict to specify 'any clay', much like the current fireclay recipe does.

**Screenshots**
Below is a screenshot of the cellar wall recipe, as an example (specifies the specific item 'clay).
![image](https://user-images.githubusercontent.com/32183732/175613216-e4a78d15-e175-454e-950e-fd4e4039cfb9.png)

**Modpack**
 - TFG-NH R3.3.5b, Huge

**Comment by Xikaro** [comment]
upgrade to 3.3.6 suddenly fixed)

**Comment by FDAapproved** [comment]
Really? That's odd, but glad to hear it's fixed. I'll close this, in that case.

**Comment by Xikaro** [comment]
No, check, maybe I'm wrong)))

**Comment by FDAapproved** [comment]
Looking at the cellarsaddon.zs file, there's no section for any altered recipes, so I'd assume this is still broken. The most you need to do is copy the original recipe (which accepts straw and any TFC lumber), and replace the clay in it. <https://github.com/SpeeeDCraft/TerraFirmaGreg-1.12.2/blob/TFG-Lite-R3.0/TFG-LITE/scripts/TerraFirmaCraft/CellarAddon.zs> Link for confirmation, also.

**Comment by Xikaro** [comment]
fixed in dev
