### ISSUE TITLE
Нет крафта Dolomite dust

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#177]
Не скрафтить третий костюм.

**Comment by SpeeeDCraft** [comment]
Эта пыль получается при переработке любой руды из доломита, чтобы ее получить нужно сделать кирку на шелк касание и выкопать блоки руды.

**Comment by nemo48rus** [comment]
Она вся генится Андезитовой и мраморной, да и те без побочек.
![image](https://user-images.githubusercontent.com/106464618/176216045-bced7c4e-2f18-4107-9f47-8dc8e82d451e.png)
![image](https://user-images.githubusercontent.com/106464618/176216264-bfef7b65-b5ab-4d3f-9f0a-c77573109982.png)

**Comment by SpeeeDCraft** [comment]
Исправлено в dev.
