### ISSUE TITLE
Clay dust and clay blocks can't be crafted

### ISSUE THREAD

**Issue by AtelierAmber** [SpeeeDCraft/TerraFirmaGreg-1.12.2#178]
**Describe the bug**
Clay dust and clay blocks can't be crafted in the macerator or compressor

**Modpack**
 - Modpack TFG Huge 3.3.6: -

**Comment by SpeeeDCraft** [comment]
Ждем, ждем, это исправит: https://github.com/GregTechCEu/GregTech/pull/666

**Comment by SpeeeDCraft** [comment]
Исправлено в следующем обновлении.
