### ISSUE TITLE
Напильники

### ISSUE THREAD

**Issue by Maximnety** [SpeeeDCraft/TerraFirmaGreg-1.12.2#18]
![2021-05-13_21 37 07](https://user-images.githubusercontent.com/84129980/118257309-87800780-b4bf-11eb-8892-7f68b58564b9.png)
![2021-05-14_14 19 53](https://user-images.githubusercontent.com/84129980/118257313-8949cb00-b4bf-11eb-86d6-7b0abed30194.png)
У многих напильников нет крафта через наковальню, даже если металл из террафирмы

**Comment by SpeeeDCraft** [comment]
Ты правда хочешь напильники? Будут тебе напильники и молотки и еще что-нибудь

**Comment by Maximnety** [comment]
> Ты правда хочешь напильники? Будут тебе напильники и молотки и еще что-нибудь

Просто с помощью ковки тратится один слиток)

**Comment by SpeeeDCraft** [comment]
Сделано.
