### ISSUE TITLE
Нет крафта

### ISSUE THREAD

**Issue by SpeeeDCraft** [SpeeeDCraft/TerraFirmaGreg-1.12.2#182]
![image](https://user-images.githubusercontent.com/52341158/176704007-b278e778-d248-46fa-975a-c7626a8d7d55.png)

**Comment by Xikaro** [comment]
![Screenshot_44](https://user-images.githubusercontent.com/55663835/176804944-414062b6-5f6f-4032-8ec6-f78b3af5d2f3.png)

**Comment by SpeeeDCraft** [comment]
У первого рецепт есть, у второго нет, потому что разраб еще не придумал каким его сделать.
