### ISSUE TITLE
Недоступный крафт субсветового двигателя.

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#183]
**Описание бага**
В крафте используются сверпрочная пластина из GalaxySpace, крафты для которых не придуманы.

**Как оно должно было работать?**
Должны были использоваться стандартные сверхпрочные пластины. Эти запретить. 
Смысла их плодить не вижу. Либо придумать 11,12, 13, 14, 15, 16 тиры, для дальнейших крафтов. Но уже достаточно дико дорогие крафты)

**Скриншоты**
![image](https://user-images.githubusercontent.com/106464618/177011497-08e2361d-5b5c-4721-8f93-bc8a8842a4ee.png)

**Comment by Xikaro** [comment]
Космос перерабатывается, смысла писать про это, нет, все будет изменено
