### ISSUE TITLE
Oven не производит тепло

### ISSUE THREAD

**Issue by Mineteller** [SpeeeDCraft/TerraFirmaGreg-1.12.2#184]
**Describe the bug**
Oven из аддона FirmaLife не производит тепла, т.е не согревает игрока, блоки этой печи игнорируются tfc ambient и проводят холод.

**To Reproduce**
Очевидно.

**Expected behavior**
Oven согревает игрока.

**Screenshots**
![2022-07-03_23 50 44](https://user-images.githubusercontent.com/108632531/177056922-fb85cac0-ca66-4c34-9a32-ce0a5eb1ec16.png)
![2022-07-03_23 50 46](https://user-images.githubusercontent.com/108632531/177056924-f35a4646-cd85-4583-b931-8e35992e85a3.png)

**Modpack**
 - Modpack TFG R3.4.1 Lite

**Comment by SpeeeDCraft** [comment]
Позже сделаем, чтобы много других блоков производило тепло.

**Comment by SpeeeDCraft** [comment]
Исправлено
