### ISSUE TITLE
Краш при клике лопатой по траве

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#187]
![Screenshot_64](https://user-images.githubusercontent.com/55663835/177876125-86bc62ef-fe6e-4395-ae6b-3e11232603dc.png)

**Comment by nemo48rus** [comment]
Пкм по передней стороне хим реактора электроотверткой крашит игру.
Баг был одноразовый, но раз пошли инструменты - пусть лежит здесь)

**Comment by SpeeeDCraft** [comment]
Исправлено в dev
