### ISSUE TITLE
Космооооооооос

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#189]
**Описание бага**
Крафт криогенной камеры не работает. Даже с цветными кроватями.

**Скриншоты**
![image](https://user-images.githubusercontent.com/106464618/178141084-147b9314-b38f-48b7-9408-374725c1f78c.png)
![image](https://user-images.githubusercontent.com/106464618/178141107-5f2b98ad-307e-44f0-adf8-27eb90b255a0.png)

**Что либо дополнительное**
Не понимаю в чём проблема. Мб в кфг стоят стёкла по бокам?

**Comment by Xikaro** [comment]
Исправлено в dev, там плотные свинцовые пластины
