### ISSUE TITLE
Рецепт инвертированных лампочек

### ISSUE THREAD

**Issue by evg-95** [SpeeeDCraft/TerraFirmaGreg-1.12.2#192]
Во всех рецептах используется соответствующий тип ламп, а в этом нет.
Думаю в рецепте ошибка.
![image](https://user-images.githubusercontent.com/5204049/179361713-ffb5f57b-d262-4aea-82cd-ec2b52a1772d.png)

**Comment by Xikaro** [comment]
Сделано в dev
