### ISSUE TITLE
Множество недоработок рецептов Алкашки из Florae.

### ISSUE THREAD

**Issue by CmBSinka** [SpeeeDCraft/TerraFirmaGreg-1.12.2#193]
Невозможность скрафтить соки из tfc florae.
Используются для крафта вина.
Так же у многих рецептов крайне странный крафт (К примеру из кактуса получить кактус).

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**
1, В поиске нам требуется ввести tfc florae в поиск вещей. (изображение 1)
2. Там мы можем найти множество крафтов различных жидкостей. (изображение 2)
3. Нас интересует крафт вина. Чтобы получить вино, нам нужен сок. У сока нету крафта. Меня это очень сильно разочаровывает. (изображение 3)

**Как оно должно было работать?**
Должен отображаться рецепт крафта.

**Скриншоты**
Предоставлены.
![image](https://user-images.githubusercontent.com/43815006/179364174-bd4e8728-1d5c-43e5-a1ab-96b8769757d1.png)
![image](https://user-images.githubusercontent.com/43815006/179364197-0a284a36-c532-430c-9530-cd0b65843b41.png)
![image](https://user-images.githubusercontent.com/43815006/179364220-49787501-e870-4860-a0cb-077f03f3ab8c.png)
![image](https://user-images.githubusercontent.com/43815006/179364256-5c3bcfd9-651a-4bca-b321-f481792b1193.png)

**Модпак**
R3.4.4 Huge.

**Что либо дополнительное**
Возможно я пропустил крафт. Но после нескольких часов поиска. я так и не нашел информацию об этом. По этому считаю что это баг.
Как я понял, так же, у всех соков из данного мода не отображается/отсутствует крафт сока.
Так же там присутствуют луки(которые стреляют стрелами), крафт которых тоже не отображается/отсутствует.
И так же многие крафты стакаются друг на друга.. (изображение 4)

**Comment by Xikaro** [comment]
Мод во многом не доработан, и как недавно объявил автор мода, что развивать далее не намерен, по этому постепенно мы сами будем его дорабатывать

**Comment by SpeeeDCraft** [comment]
Исправлено в dev
