### ISSUE TITLE
Инженерный верстак делает из меди красную сталь

### ISSUE THREAD

**Issue by TysoN-Rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#194]
В инженерном верстаке можно заменить неформованный слиток любым металлом, без изменения результата крафта.
 
Шаги для воспроизведения поведения:
1. Поставить инженерный верстак.
2. Положить в него 1 "Неформованный слиток красной стали" (холодный)
3. Положить в него 3-5 "Неформованный слиток меди" (холодные)
4. Разместить в сетке крафта "Неформованный слиток красной стали"
5. Произвести крафт "Красная сталь (Слиток)"
6. Разместить в сетке крафта "Неформованный слиток меди" на место "Неформованный слиток красной стали"
7. Произвести крафт

**Фактическое поведение**
Из "Неформованный слиток меди" извлекается "Красная сталь (Слиток)". 
Работает с любыми металлами в любой комбинации

**Ожидаемое поведение**
Из "Неформованный слиток меди" извлекается "Медь (Слиток)"

**Modpack**
 - Modpack TFG, R3.4.4, Lite

**YouTube**
https://www.youtube.com/watch?v=PKj3mWo7cl4

**Comment by Xikaro** [comment]
К сожалению, проблема известна, и сообщена разрабам, с этим верстаком куча проблем, и как сообщили разработчики, в релизу мода, баги должны быть пофикшены, нам остается просто ждать
