### ISSUE TITLE
Зашёл, зарегался умер. Hardest modpack (c)

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#196]
**Описание бага**
Зашёл на серв, чтобы расслабиться и почиллить, а попал на мачту и спуститься даже нормально не смог - сдох.
20 минут чилить на спауне - каеф.

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**
Зарегаться.
Умереть.

**Comment by Xikaro** [comment]
Hardest modpack (c)
