### ISSUE TITLE
Доп. совместимость с GTCEu

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#197]
**Описание того, что вы хотите, чтобы мы сделали**

В связи с адаптацией TFC под GT (вместо 100 единиц на слиток, 144ед.) народ хочет, чтобы влезало в тигель столько же единиц металла, как и раньше: на 30 слитков - 4320;
раз уж лезть, то может сразу 32?
Тогда будет 4608.

**Comment by SpeeeDCraft** [comment]
Выполнено.
