### ISSUE TITLE
Missing mod in server files

### ISSUE THREAD

**Issue by JulianVennen** [SpeeeDCraft/TerraFirmaGreg-1.12.2#198]
**Describe the bug**
The server files for R4.0.0 are missing the mod [CB Multipart](https://www.curseforge.com/minecraft/mc-mods/cb-multipart/files/2755790)

**To Reproduce**
1. Download the server files from curseforge
2. Extract them and start the forge jar
3. See the crash error

**Modpack**
 - TerraFirmaGreg: New Horizons R4.0

**Additional context**
Log: https://mclo.gs/dG8HuUX#L312

**Comment by Xikaro** [comment]
Fixed, uploaded to the course

**Comment by JulianVennen** [comment]
Wow, that was really fast 👍🏻
