### ISSUE TITLE
Неверный крафт формы для ножа

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#199]
**Как оно должно было работать?**
Ct не меняет крафт формы ножа, как задумано. Делает как в оригинальном gt блок.

**Скриншоты**
![image](https://user-images.githubusercontent.com/106464618/182045531-1a3d76f7-ab1b-403e-bc4c-4a059d12166d.png)
Теория
![image](https://user-images.githubusercontent.com/106464618/182045554-54b516e5-fc58-4ec7-9477-40a47a09b571.png)
Практика

**Comment by Xikaro** [comment]
дубль рецепта, пофикшено в дев
