### ISSUE TITLE
Невозможность для новых игроков скрафтить мэ терминал крафта

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#200]
![image](https://user-images.githubusercontent.com/106464618/183220952-aa7abdd7-2189-440e-9df5-d686f5b77ea9.png)
![image](https://user-images.githubusercontent.com/106464618/183220961-ae7d4ebf-f7f3-4d0f-b60d-1a5f8807f1c0.png)

**Comment by nemo48rus** [comment]
![image](https://user-images.githubusercontent.com/106464618/183222917-41e01ad1-a13e-427e-9932-dd5679b89c19.png)
Не имеет крафта

**Comment by SpeeeDCraft** [comment]
Исправлено в dev
