### ISSUE TITLE
Мод  - Cyberware (Robotic Parts) (киберпанк в майнкрафте)

### ISSUE THREAD

**Issue by ABAHrAPD** [SpeeeDCraft/TerraFirmaGreg-1.12.2#210]
Ссылка на сам мод  - https://www.curseforge.com/minecraft/mc-mods/roboticparts 

Обзор на мод - https://www.youtube.com/watch?v=uPfpv_nKZ4U

**Comment by SpeeeDCraft** [comment]
Не в нашем модпаке, сорри
