### ISSUE TITLE
Добавление мода Xtones

### ISSUE THREAD

**Issue by AinGraceful** [SpeeeDCraft/TerraFirmaGreg-1.12.2#212]
**_Мод который добавляет больше декоративных блоков_**

Ссылка на мод : https://www.curseforge.com/minecraft/mc-mods/xtones

**Comment by ABAHrAPD** [comment]
так есть же мод чизель и там полным полно декор блоков а так же

**Comment by AinGraceful** [comment]
декор блоков много не бывает!

**Comment by Xikaro** [comment]
Добавлен в обновлении 4.1.1
