### ISSUE TITLE
Светящиеся блоки

### ISSUE THREAD

**Issue by TheGalaxx** [SpeeeDCraft/TerraFirmaGreg-1.12.2#213]
Добавить блоки, имеющие постоянную светимость, как у катушек доменки во время работы

**Comment by Xikaro** [comment]
Уже в процессе работы

**Comment by Xikaro** [comment]
![Screenshot_43](https://user-images.githubusercontent.com/55663835/186890051-d43cadd1-b553-4131-bcf9-58babe204eb5.png)
