### ISSUE TITLE
Дубль рецептов при смешивании

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#216]
![image](https://user-images.githubusercontent.com/106464618/187299979-d265e322-cd07-454f-a20f-533ee9b11ceb.png)

**Comment by Xikaro** [comment]
исправлено в dev

**Comment by nemo48rus** [comment]
![image](https://user-images.githubusercontent.com/106464618/187300301-ac61f894-9957-4a3b-8f84-4c1c24e4458b.png)

**Comment by Xikaro** [comment]
это в чем рецепт?

**Comment by Xikaro** [comment]
и первая ошибка, почему у тебя 4 листа рецептов в смесителе?
