### ISSUE TITLE
Рецепты для флюса и графита в ступке

### ISSUE THREAD

**Issue by SpeeeDCraft** [SpeeeDCraft/TerraFirmaGreg-1.12.2#218]
![image](https://user-images.githubusercontent.com/52341158/187568343-e103fc32-fcd6-424d-8d79-91edc3163f45.png)

**Comment by Xikaro** [comment]
Сделано в дев

**Comment by nemo48rus** [comment]
А в дробилку можно? Каоленит есть, графита нету по моему и ещё какая то третья пыль была, в вулканизирующем кажется

**Comment by Xikaro** [comment]
Сделано
