### ISSUE TITLE
при ломании Workbench Plus вещи из него удаляются

### ISSUE THREAD

**Issue by FriendlyCube** [SpeeeDCraft/TerraFirmaGreg-1.12.2#219]
**Описание бага**
при ломании Workbench Plus вещи из него удаляются

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**
1. Идти туда 'поставить Workbench Plus '
2. Нажать сюда 'войти в верстак и положить вещи'
3. Пролистнуть сюда 'сломать верстак'
4. Увидеть ошибку

**Как оно должно было работать?** 
Что должно было произойти? 
оно не должно было удалять предмета сука

**Скриншоты**
Скриншоты проблемы.
и без них понятно

**Модпак**
 - Версия TFG R4.1.1, Lite -

**Что либо дополнительное**
мне же вищи не вернут да

**Comment by FriendlyCube** [comment]
Версия TFG R4.1.1, Normal - *

**Comment by Xikaro** [comment]
Исправлено в дев, мод удален
