### ISSUE TITLE
Unfired hammer head mold is uncraftable

### ISSUE THREAD

**Issue by Amakazor** [SpeeeDCraft/TerraFirmaGreg-1.12.2#22]
**Describe the bug**
Unfired hammer head mold is uncraftable

**To Reproduce**
1. Look in JEI for recipes for unfired hammer head mold
2. Try crafting it using any available combination
3. It's impossible to craft

**Expected behavior**
Unfired hammer head mold should be able to be crafted

**Modpack Version:**
R2.6.6

**Comment by SpeeeDCraft** [comment]
It's all right, it's as planned, you can forge a copper hammer on a stone anvil, and you'll need a hammer mold.
