### ISSUE TITLE
UV контроллер напряжения

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#223]
Рецепт отвалился
![image](https://user-images.githubusercontent.com/106464618/187898829-884f94ed-d379-475a-8000-80fdff7314d4.png)

**Comment by Xikaro** [comment]
Еще не реализовано на стороне GT

**Comment by nemo48rus** [comment]
Всмысле ?! Ничего что в прошлом вайпе UHV ставил на мехи?

**Comment by Xikaro** [comment]
тогда вопрос, зачем они его делитнули

**Comment by Xikaro** [comment]
а не помнишь из чего он был?

**Comment by TheGalaxx** [comment]
8 дармштадтия(или амерция, вобщем того, из чего корпуса ув делаются) и UHV микросхема

**Comment by Xikaro** [comment]
Добавил в дев

**Comment by nemo48rus** [comment]
Скорее всего случайно не допилили совместимость с грегосайенс, там
нейтроний идёт дальше по цепочке крафтов

вс, 4 сент. 2022 г., 10:00 Xikaro ***@***.***>:

**Comment by Xikaro** [comment]
![Screenshot_61](https://user-images.githubusercontent.com/55663835/188359039-0873d54b-69ff-411c-a90a-aea8b6d6d20f.png)
Вот где UV контролер

**Comment by TheGalaxx** [comment]
3 термояд, необходимый для получения требует ув сборщик, а из-за отстутствия блока контроля напряжения надо делать одноблочный

**Comment by Xikaro** [comment]
да сделал я уже рецепт, узбагайся
