### ISSUE TITLE
 ExtraCPUs баг

### ISSUE THREAD

**Issue by nemo48rus** [SpeeeDCraft/TerraFirmaGreg-1.12.2#227]
256 CPU не подкидывается в новый терминал просмотра крафтов и в системе в принципе не работает
![2022-09-01_23-06-17](https://user-images.githubusercontent.com/106464618/188002820-87d87fee-8225-4759-85e4-0f44098407fe.png)
![image](https://user-images.githubusercontent.com/106464618/188002893-2550b311-bff7-4157-b8f3-e23205664325.png)
Пробовал запускать вообще только с 256 - цпу не найдены.

**Comment by nemo48rus** [comment]
Больше всего боюсь того, что все остальные процы тоже не заработают с новым GUI и AE2EL

**Comment by Xikaro** [comment]
Да, 256к не работает в одиночку, стоит об этом дописать, это из-за особенности кода ае, т.е его надо использоваться в совокупности с стандартными цпу, по поводу отображения, аналогично, это бекпорт, и по этому пока совместимости нет, запрошу эту функцию

**Comment by Xikaro** [comment]
Не понятно, они в принципе не работают, или работаю, но с другим цпу? И просто не отображаются в боковой панели?

**Comment by nemo48rus** [comment]
![image](https://user-images.githubusercontent.com/106464618/188020883-2f08068b-2d52-4871-858e-5b76c2302483.png)
По одиночке он не хочет видить блоки extracpu, но если на него насрать процом от 1к до 64к из AE2EL, то начинает видеть

**Comment by Xikaro** [comment]
Что я выше и написала, это норма
