### ISSUE TITLE
Стекло термояда для герметичных зданий

### ISSUE THREAD

**Issue by TheGalaxx** [SpeeeDCraft/TerraFirmaGreg-1.12.2#231]
Сделать стекло термояда герметичным блоком(как вакуумное стекло), т.к сейчас нету прозрачных блоков, для строительства обьектов в космосе.

**Comment by Xikaro** [comment]
Little tiles, как вариант

**Comment by Xikaro** [comment]
Стекло GT тоже теперь подходит
