### ISSUE TITLE
Certus Ore gen looks broken - does not appear in OverWorld

### ISSUE THREAD

**Issue by AMZN-Olex** [SpeeeDCraft/TerraFirmaGreg-1.12.2#28]
**Describe the bug**
I spent quite a while looking for Certus ore with Prospector MV. I found Iridium twice but never certus ore. Until I looked into config files:

earth_quartz_vein.json
{
  "weight": 70,
  "density": 0.4,
  "min_height": 55,
  "surface_stone_material": "quartzite",
  "generation_predicate":["ore_dict:GenQuartzite"],

I don't see any other ore gens use "ore_dict:GenQuartzite", once I changed it to "any". Certus began to appear easily.

**Comment by SpeeeDCraft** [comment]
Thanks. Fixed :D
