### ISSUE TITLE
Yellow Garnet Ore is required for AE in this modpack but is more than Iridium to find

### ISSUE THREAD

**Issue by AMZN-Olex** [SpeeeDCraft/TerraFirmaGreg-1.12.2#29]
**Describe the bug**
Engineering Press for AE2 requires yellow garnet, but in earth_yellow_garnet_vein.json it has a weight of 10, whereas even Iridium has weight of 20. That is far too rare to get into AE2.

Locally, on my server, I bumped that up but it should be a concern to address in this modpack.

Thanks!

**Comment by SpeeeDCraft** [comment]
I agree with you, I will increase its number in the next update.
