### ISSUE TITLE
Кривая локализация железа

### ISSUE THREAD

**Issue by SpeeeDCraft** [SpeeeDCraft/TerraFirmaGreg-1.12.2#3]

**Comment by Xikaro** [comment]
переименовывать в скрипте Rename?

**Comment by SpeeeDCraft** [comment]
> переименовывать в скрипте Rename?

Я уже сделал :)

**Comment by Xikaro** [comment]
а если остальное переименовывать, там же?

**Comment by SpeeeDCraft** [comment]
> а если остальное переименовывать, там же?

Да, но поидее этим утка должен был заняться, мне бы лучше ты бы настроил лут в данжах WarpDrive, лучше сделать файл обычный, ну тоесть перегенерировать, который с лутом /config/WarpDrive/loot че то там, и позаменять все на что-то крутое.
