### ISSUE TITLE
AE2 Network Tool is not craftable

### ISSUE THREAD

**Issue by AMZN-Olex** [SpeeeDCraft/TerraFirmaGreg-1.12.2#30]
AE2 Network Tool is not available for crafting.
GT wrenches don't pop AE cables and parts without breaking the entire block.
AE2 is a pain to work without its network tool.

Could this be enabled back? Thanks!

![image](https://user-images.githubusercontent.com/5432499/128601279-6587fb03-b193-4ee5-948a-d90379961760.png)

**Comment by SpeeeDCraft** [comment]
Already ixed in R2.8
