### ISSUE TITLE
AE2 Flat ME Interface is not craftable

### ISSUE THREAD

**Issue by AMZN-Olex** [SpeeeDCraft/TerraFirmaGreg-1.12.2#33]
![image](https://user-images.githubusercontent.com/5432499/129276174-4786fac9-7019-4bba-8629-1ee8c3ffbab7.png)

**Comment by SpeeeDCraft** [comment]
![image](https://user-images.githubusercontent.com/52341158/129297324-e57cfebd-de2e-4f82-b810-8a28c6ec6ed6.png)
