### ISSUE TITLE
Diamond Grit Honing Steel is not craftable

### ISSUE THREAD

**Issue by AMZN-Olex** [SpeeeDCraft/TerraFirmaGreg-1.12.2#35]
It takes a diamond dust to craft it.

![image](https://user-images.githubusercontent.com/5432499/129448687-e2dcfba3-b62d-40d8-8c24-7ae8b2857119.png)

But diamond dust is not place-able into an anvil. (Tested with blue anvil.)

**Comment by SpeeeDCraft** [comment]
fixed
