### ISSUE TITLE
[2.8.4] AE2 Memory Card is broken

### ISSUE THREAD

**Issue by AMZN-Olex** [SpeeeDCraft/TerraFirmaGreg-1.12.2#37]
**Describe the bug**

Shift-clicking on "P2P tunnel - ME" ignores the tunnel and clears the machine.
Right clicking on ME tunnels gives "invalid machine."

See the screenshot below:

![image](https://user-images.githubusercontent.com/5432499/129821915-c05e88ce-8609-4efe-95a8-fec77b65b760.png)

P.S. I've tried on both online and offline tunnels. The same operations worked in 2.8.2 and earlier.

**Comment by SpeeeDCraft** [comment]
Perhaps it was an AE2 bug
