### ISSUE TITLE
2.8.5 - High Pressure Steam Furnace recipe is broken

### ISSUE THREAD

**Issue by AMZN-Olex** [SpeeeDCraft/TerraFirmaGreg-1.12.2#38]
**Describe the bug**

High Pressure Steam Furnace recipe is broken as it requires itself to make itself.

![image](https://user-images.githubusercontent.com/5432499/130239939-463fc7e4-9bbe-4f3d-b03c-eb1e9783b6b2.png)

**Comment by SpeeeDCraft** [comment]
fixed
