### ISSUE TITLE
Проблема отображения текстур

### ISSUE THREAD

**Issue by GreatOdin2002** [SpeeeDCraft/TerraFirmaGreg-1.12.2#40]
Во время выкапывания самородков металлов перед их разрушением они меняют текстуру на алюминиевые самородки.

**Comment by SpeeeDCraft** [comment]
Это не проблема TFG. Скорее всего это баг GT. Но так как я не нашел ничего связанного с твоей проблемой у них в ошибках, это означает, что ошибка на твоей стороне. Возможно медленный жёсткий диск. Или слабый ПК. И он просто не успевает все отобразить, поэтому ты видишь промежуточные результаты. А может это Оптифайн все косячит. Главное, что я это не могу исправить. Даже если бы хотел.
