### ISSUE TITLE
Проблема с листвой в воздухе

### ISSUE THREAD

**Issue by GreatOdin2002** [SpeeeDCraft/TerraFirmaGreg-1.12.2#41]
Проблема с Dynamic Trees
![2021-08-28_11 08 31](https://user-images.githubusercontent.com/89649133/131211284-e2e3a7a5-e1af-4002-94b0-d36459512389.png)

- [ ] 

- [ ]

**Comment by SpeeeDCraft** [comment]
Проблема уже описана на гите у разрабов DynamicTreesTFC. Я никак не могу помочь.
