### ISSUE TITLE
Крафт ванильного хлеба

### ISSUE THREAD

**Issue by GreatOdin2002** [SpeeeDCraft/TerraFirmaGreg-1.12.2#42]
![2021-08-28_11 52 27](https://user-images.githubusercontent.com/89649133/131212362-2abaf194-14c4-457d-ac55-fb5153fe2780.png)
![2021-08-28_11 52 39](https://user-images.githubusercontent.com/89649133/131212365-d30c34e2-9731-4499-8dbf-102f61bdb846.png)
![2021-08-28_11 52 42](https://user-images.githubusercontent.com/89649133/131212367-e0057f23-f2be-4847-845a-e04069ec7239.png)

**Comment by SpeeeDCraft** [comment]
Понял. Исправим.
