### ISSUE TITLE
Кулинария

### ISSUE THREAD

**Issue by GreatOdin2002** [SpeeeDCraft/TerraFirmaGreg-1.12.2#46]
Предлагаю добавить новые рецепты приготовления пищи и невозможность употреблять сырое мясо.

**Comment by GreatOdin2002** [comment]
Также было бы неплохо сделать возможность получать пресную воду из солёной

**Comment by GreatOdin2002** [comment]
или степень загрязнения воды с её обработкой

**Comment by GreatOdin2002** [comment]
как и систему температуры персонажа

**Comment by GreatOdin2002** [comment]
Просто предлагаю)

**Comment by SpeeeDCraft** [comment]
Все это не могу добавить я. Хоть и хотел бы. Пиши разрабу TFC.
