### ISSUE TITLE
Спавн структур из астрал сорсери

### ISSUE THREAD

**Issue by GreatOdin2002** [SpeeeDCraft/TerraFirmaGreg-1.12.2#47]
![2021-08-31_22 43 08](https://user-images.githubusercontent.com/89649133/131566176-f872211a-3ca5-4004-892a-c3b1993d5c3c.png)

**Comment by GreatOdin2002** [comment]
Так и должно быть?
Не вписываеться в атомосферу

**Comment by SpeeeDCraft** [comment]
> Так и должно быть?
> Не вписываеться в атомосферу

Нет

**Comment by SpeeeDCraft** [comment]
Исправлено.
