### ISSUE TITLE
Ванильные алмазы

### ISSUE THREAD

**Issue by GreatOdin2002** [SpeeeDCraft/TerraFirmaGreg-1.12.2#49]
Они используются в рецептах, но их нельзя получить.
![2021-09-04_18 11 43](https://user-images.githubusercontent.com/89649133/132099321-408d23b2-3f2f-4302-b53d-9e4e29e68496.png)

**Comment by VikramY22** [comment]
Распакуй блок алмазов в распаковщике используя схему 3х3, получишь ванильные алмазы.

**Comment by SpeeeDCraft** [comment]
Исправим.

**Comment by SpeeeDCraft** [comment]
Исправлено.
