### ISSUE TITLE
Бесполезная пчелиная матка

### ISSUE THREAD

**Issue by GreatOdin2002** [SpeeeDCraft/TerraFirmaGreg-1.12.2#50]
![2021-09-04_18 15 30](https://user-images.githubusercontent.com/89649133/132099406-1396bdeb-6674-4f5a-bb08-583a70e9ad6e.png)
![2021-09-04_18 16 02](https://user-images.githubusercontent.com/89649133/132099410-cd8f0450-d3e8-4079-8c11-2096543bd83e.png)

**Comment by SpeeeDCraft** [comment]
Исправим в след. обновлении.

**Comment by SpeeeDCraft** [comment]
Удалены рецепты связанные с пчелами из Pams HarvestCraft, тк для это цели есть форестри.

**Comment by GreatOdin2002** [comment]
> Удалены рецепты связанные с пчелами из Pams HarvestCraft, тк для это цели есть форестри.

А спавн ульев удалён?

**Comment by SpeeeDCraft** [comment]
Да
