### ISSUE TITLE
Неразличимый текст таумкрафта (аспекты)

### ISSUE THREAD

**Issue by GreatOdin2002** [SpeeeDCraft/TerraFirmaGreg-1.12.2#51]

**Comment by SpeeeDCraft** [comment]
Исправляется установкой большого интерфейса в настройках графики. С моей стороны никак это исправить не могу.

**Comment by GreatOdin2002** [comment]
Если у кого-то тоже не меняется интерфейс.
[Новая папка.zip](https://github.com/SpeeeDCraft/TerraFirmaGreg-1.12.2/files/7120543/default.zip)
