### ISSUE TITLE
[Bug] Fluid Bowl recipe didn't consume ceramic bowl

### ISSUE THREAD

**Issue by kotoroshinoto** [SpeeeDCraft/TerraFirmaGreg-1.12.2#55]
**Describe the bug**
Ceramic Fluid Bowl recipe didn't consume ceramic bowl.

**To Reproduce**
Make ceramic bowl or pull fired bowl from JEI
Place into crafting grid, and attempt to pull liquid bowl item off of result box

Receive liquid bowls without consuming original bowls

**Expected behavior**
Receive equivalent number of liquid bowls while regular ceramic bowl items are consumed.

**Modpack**
 - Modpack TFG(R2.9, Huge): -

**Additional context**
Don't seem to be able to use the bowls, bowl mount or grooves at all in the huge version of the pack. Has a method been developed to work around the need for latex when dynamic trees  mods are active?

**Comment by SpeeeDCraft** [comment]
Fixed
