### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#57]
- [x] Не работает статус бар жажды, а сама жажда  работает, и делает больно
- [x] в бочке делается глина из воды, рецепт есть, получить не удалось

![Screenshot_113](https://user-images.githubusercontent.com/55663835/144651898-e1e5a18d-687b-4d75-b819-5af6d01c2458.png)

- [x] не работаю молот с зубилом

**Comment by SpeeeDCraft** [comment]
Исправлено
