### ISSUE TITLE
молот gt не разрушает руду gt на серве

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#58]
при попытке разрушить блок руды молотом, он исчезает и превращается в фантомный, но не выпадает

**Comment by Xikaro** [comment]
![Screenshot_118](https://user-images.githubusercontent.com/55663835/144680186-bedfcd05-b17b-4f97-aebe-87d1be2fe4ae.png)
на сервере и клиенте, ошибка повторилась, прикладываю лог
[latest.log](https://github.com/SpeeeDCraft/TerraFirmaGreg-1.12.2/files/7652641/latest.log)
просто в сингле, ошибка не воспроизводится

**Comment by SpeeeDCraft** [comment]
Исправлено в новой версии GT
