### ISSUE TITLE
Сундук из Гевеи имеет два крафта, в отличии от других сундуков, имеющих один крафт

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#59]
**Описание бага**
Сундук из Гевеи имеет два крафта, в отличии от других сундуков, имеющих один крафт

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**
1.Посмотреть в jei
2. Увидеть ошибку

**Как оно должно было работать?**
Иметь один крафт
Что должно было произойти?

**Скриншоты**

![Screenshot_120](https://user-images.githubusercontent.com/55663835/144681817-b55272d7-2492-42d3-b2ef-3ee592bf1aea.png)
![Screenshot_119](https://user-images.githubusercontent.com/55663835/144681825-afe65295-110a-43fb-a20e-d0e365087213.png)
**Модпак**
 - Версия TFG R3.0.0-beta-101 -

**Что либо дополнительное**
Возможно это фича
Так как рецепт добавляется TFK-Tech

**Comment by SpeeeDCraft** [comment]
Исправлено
