### ISSUE TITLE
Не сплавляются слитки меди на наковальне 0 уровня

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#60]
**Описание бага**
При попытке сплавить два слитка меди в двойной слиток, на наковальне 0 уровня, ничего не получается

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**
1. Разогреть два слитка меди
![Screenshot_124](https://user-images.githubusercontent.com/55663835/144682685-bf28dfff-7440-4978-b923-de64cc747051.png)
2. Переложить в наковальню 0 уровня, и положить флюс
![Screenshot_123](https://user-images.githubusercontent.com/55663835/144682752-af2175e3-8a88-4da7-a6e1-5cb297900ea1.png)

3. Выйти из меню наковальни и ударить по наковальне
![Screenshot_122](https://user-images.githubusercontent.com/55663835/144682868-d6935576-8848-4150-a3af-889e78e3e0ae.png)
4. Увидеть ошибку

**Как оно должно было работать?**
Превратится в двойной слиток

**Модпак**
 - Версия TFGR3.0.0-beta-101 -

**Comment by SpeeeDCraft** [comment]
Исправлено
