### ISSUE TITLE
Отсутствие рецептов

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#61]
**Описание бага**
Нет рецептов

- [x] Horse Chopping Block
- [x] Отсутствует крафт каменного молота
- [x] Отсутствует большая часть крафтов для Lumber, через пилу GT
- [x] impregnated casing и impregnated stick

**Comment by Xikaro** [comment]
у Lumber нет рецептов не только из флоры, но и tfc, а так нет рецептов переработки Pole из FirmaLife, возможно из-за уже известной ошибки с Florae

**Comment by SpeeeDCraft** [comment]
Исправлено
