### ISSUE TITLE
Не правильные рецепты

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#62]
**Описание бага**
В рецептах присутствуют предметы, которых нет 

**Как воспроизвести?**
1. Зайти в Jei
2. Увидеть ошибку
Ошибка рецептов

![Screenshot_114](https://user-images.githubusercontent.com/55663835/144658881-f4b34bf1-978a-4aa7-b031-89c375c1e2a7.png)
![Screenshot_115](https://user-images.githubusercontent.com/55663835/144659035-3959b3ba-d1e0-438b-9208-f86a08426f6e.png)

**Модпак**
 - Версия TFG R3.0.0-beta-101 -

**Comment by SpeeeDCraft** [comment]
Исправлено
