### ISSUE TITLE
Нет рецепта Bloomery

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#63]
**Описание бага**
Нет рецепта Bloomery

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**
1. Найти в jei Bloomery
2. Увидеть отсутствие рецепта

**Как оно должно было работать?**
Должен быть рецепт из двойных пластин любой из трех бронз как ниже

**Скриншоты**
![Screenshot_132](https://user-images.githubusercontent.com/55663835/144724235-cb7da6cd-4016-472d-9c63-0705b3364f21.png)

**Модпак**
 - Версия TFG(R3.0.0-beta-102): -

**Что либо дополнительное**
Возможно из-за унификации пластин с GT, у пластин отсутствует ордикт <ore:sheetDoubleAnyBronze>

**Comment by SpeeeDCraft** [comment]
Исправлено
