### ISSUE TITLE
нет рецепта Empty Wooden Form

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#64]
**Описание бага**
нет рецепта Empty Wooden Form, точнее скорее всего конфликт рецептов

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**

1. Найти в jei Empty Wooden Form
2. Увидеть отсутствие рецепта

**Как оно должно было работать?**
Должен быть рецепт как на скриншоте ниже

**Скриншоты**
![Screenshot_133](https://user-images.githubusercontent.com/55663835/144724472-649a7d65-5703-4a64-a4f9-bcaa8798befc.png)

![Screenshot_135](https://user-images.githubusercontent.com/55663835/144724754-b8caa983-c462-4a92-aa15-5d224e5d814f.png)
**Модпак**
 - Версия TFG (R3.0.0-beta-102): -

**Comment by SpeeeDCraft** [comment]
Исправлено
