### ISSUE TITLE
[Bug] У некоторой пищи нет статов

### ISSUE THREAD

**Issue by AlgorithmLX** [SpeeeDCraft/TerraFirmaGreg-1.12.2#66]
**Описание бага**
При перемещении земли(а точнее при её падении) ломается дерево из DynamicTrees

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**
кликать пкм по дереву

**Модпак**
 - Версия TFG(Номер версии и ее тип(например: R2.8.8, Lite)): - TFG 2.9.1 HUGE
**Видео**
https://youtu.be/WAwmJLBWGAE

**Comment by AlgorithmLX** [comment]
баг n2. некоторая еда не имеет в питании данных, и не какой пункт питания не повышается.
![image](https://user-images.githubusercontent.com/46783751/144838480-5610b26f-439c-4ca5-90f8-4eafc181b8a8.png)
![image](https://user-images.githubusercontent.com/46783751/144838687-141bcd2b-6f68-4e39-b857-09ff001b5acd.png)
![image](https://user-images.githubusercontent.com/46783751/144838647-1d8cc80c-4f30-4797-94a0-dba7d8464493.png)

**Comment by SpeeeDCraft** [comment]
Фича тфк, это не баг, логично, если ты съешь сырое тесто, чувствовать ты себя будешь плохо, это же относится и к другим таким же предметам.
