### ISSUE TITLE
[BUG] Нет рецепта у оголовий пил

### ISSUE THREAD

**Issue by lolikill51** [SpeeeDCraft/TerraFirmaGreg-1.12.2#67]
У лезвия пилы есть крафт через отливку, через крафт в инвентаре с помощью пластин и инструментов, НО НЕТ крафта через ковку (медь, бронза(висмутовая, чёрная, обычная), железо, сталь(обычная, чёрная, красная, синяя))

**Comment by SpeeeDCraft** [comment]
Исправил.
