### ISSUE TITLE
DynamicTrees for Thaumcraft addons[Bug]

### ISSUE THREAD

**Issue by AlgorithmLX** [SpeeeDCraft/TerraFirmaGreg-1.12.2#68]
**Описание бага**
Четкое и краткое описание того, в чем заключается ошибка.

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**

Найти дерево из Thaumcraft.

**Как оно должно было работать?**
Должно было быть дерево не из Thaumcraft, а из DynamicTrees for Thaumcraft addons

**Скриншоты**
![image](https://user-images.githubusercontent.com/46783751/145210502-b0052964-c78d-4d73-bc67-540aa9257e86.png)

**Модпак**
 - Версия TFG(Номер версии и ее тип(например: R2.8.8, Lite)): - 2.9.1 HUGE

**Что либо дополнительное**
Это просто примечание.

В модпаке установлен аддон для Thaumcraft и DynamicTrees -  DynamicTrees for Thaumcraft addons
![image](https://user-images.githubusercontent.com/46783751/145211154-c5e1f098-2d88-4470-b845-8525bfa9e5db.png)
https://github.com/SpeeeDCraft/TerraFirmaGreg-1.12.2/blob/R2.0/TFG-HUGE/mods/DynamicTreesThaumcraftAddons-1.12.2-1.1.3.jar
однако когда бегаешь по миру, генерируются обычные деревья

**Comment by SpeeeDCraft** [comment]
Так задуман мод, поэтому это не баг

**Comment by AlgorithmLX** [comment]
Понял
