### ISSUE TITLE
[BUG] Лист ошибок

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#69]
**Описание бага**

- [x] Пыли железа не добавлена сколько содержит металла ( нельзя использовать для крицы)
- [x] Инжеренерный верстак нельзя скрафтить, так как использует дерево из обычного Майна
- [x] Квест на сталь, зависит от кожи из сушеного ананаса, что мешает продвижению по квестам
- [x] Паровая буровая установка должна крафтиться из 2 средних алмазов ?

**Модпак**
 - Версия TFG(R3.0.0-beta-105)): -

**Comment by SpeeeDCraft** [comment]
Исправлено.
