### ISSUE TITLE
[BUG] Коксовая печь не принимает битумный уголь

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#70]
**Описание бага**
Коксовая печь не принимает со старта битумный уголь

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**
1. Зайти в коксовую печь
2. Положить битумный уголь из тфк
3. Увидеть ошибку

**Как оно должно было работать?**
Должен был сделаться кокс
![Screenshot_3](https://user-images.githubusercontent.com/55663835/145278279-2c4128e5-ffac-4255-9926-e07313ea72f5.png)
![Screenshot_2](https://user-images.githubusercontent.com/55663835/145278280-0e030db0-a887-4a29-bf39-6da9080e60ae.png)
![Screenshot_1](https://user-images.githubusercontent.com/55663835/145278282-49b81938-fbf9-40e2-b0fe-767dd27f6181.png)

**Скриншоты**
Скриншоты проблемы.

**Модпак**
 - Версия TFG(R3.0.0-beta-105): -

**Что либо дополнительное**
При чем обычный уголь из майна работает
Дополню, что если положить обычный уголь, а после него битумный, то и битумный переработается

**Comment by SpeeeDCraft** [comment]
Баг в моде GT уже написал им об этом.
