### ISSUE TITLE
[BUG] Ведра делаются из листов ТФК, а не из пластин ГТ

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#71]
**Описание бага**
В крафте ведер из тфк, используются пластины тфк

**Скриншоты**
![Screenshot_5](https://user-images.githubusercontent.com/55663835/145278761-fab0c3e9-7d65-4046-aa7c-07dfc2f909dd.png)
![Screenshot_4](https://user-images.githubusercontent.com/55663835/145278793-b24d23a6-ad09-46b7-8c93-8ace570076a4.png)

Что должно было произойти?
Должны использоваться пластины грегтеч

**Модпак**
 - Версия TFG(R3.0.0-beta-105): -

**Comment by SpeeeDCraft** [comment]
Исправлено.
