### ISSUE TITLE
держатель горшка

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#72]
**Описание бага**
В крафте тфк держателя горшка, используется кованое железо тфк

**Как оно должно было работать?**
Должно использоваться гт кованное железо 

**Скриншоты**
![Screenshot_10](https://user-images.githubusercontent.com/55663835/145303900-ff8e1750-aa09-4ef3-91b4-4748ea46b045.png)
![Screenshot_11](https://user-images.githubusercontent.com/55663835/145303909-e2b4eeda-cef0-4e3f-ab9a-8a20d125b519.png)

**Модпак**
 - Версия TFG(R3.0.0-beta-105): -

**Что либо дополнительное**
слиток кованного железа можно получить долбанув крицу в наковальне

**Comment by SpeeeDCraft** [comment]
Исправлено.
