### ISSUE TITLE
[Bug] Исправить рецепт лейки из firmalife

### ISSUE THREAD

**Issue by SpeeeDCraft** [SpeeeDCraft/TerraFirmaGreg-1.12.2#76]
**Исправить рецепт лейки из firmalife**

**Comment by Xikaro** [comment]
<firmalife:sprinkler>
![Screenshot_28](https://user-images.githubusercontent.com/55663835/151659137-b27ca139-430a-4c4b-a429-425f98976dec.png)
![Screenshot_27](https://user-images.githubusercontent.com/55663835/151659138-f6494884-2478-4a68-a228-94802e1851da.png)

**Comment by Xikaro** [comment]
сделано
