### ISSUE TITLE
[Feature]Добавление обработки видов стали в механическом молоте из GT

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#78]
Щас так
![Screenshot_4](https://user-images.githubusercontent.com/55663835/152262960-cb326a2f-a40c-4c39-af6c-f59660be7c97.png)
а должно быть так
![Screenshot_5](https://user-images.githubusercontent.com/55663835/152262968-ef844409-04f9-456c-ba89-6d244830ce5a.png)

**Comment by SpeeeDCraft** [comment]
Исправлено.
