### ISSUE TITLE
[Bug]Заменить в рецептах ванильный булыжник, на булыжник тфк

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#79]
![Screenshot_6](https://user-images.githubusercontent.com/55663835/152263189-a842b3bd-db72-4e9f-a81b-7c5f4c7bf396.png)
![Screenshot_9](https://user-images.githubusercontent.com/55663835/152263195-40c1d07d-0694-4051-9c4e-299e3aed840c.png)
![Screenshot_8](https://user-images.githubusercontent.com/55663835/152263197-4bf81a6c-e83c-4e14-ad11-2b8ecaa3277d.png)
![Screenshot_7](https://user-images.githubusercontent.com/55663835/152263198-7f0a16e7-c677-42aa-b8d0-b4deb1764f23.png)

**Comment by SpeeeDCraft** [comment]
Легчайший фикс.
