### ISSUE TITLE
[Bug] Нету крафта примитивных кирпичей

### ISSUE THREAD

**Issue by Damodigy** [SpeeeDCraft/TerraFirmaGreg-1.12.2#83]
**Описание бага**
Нету крафта примитивных кирпичей

**Как воспроизвести?(Вы должны заменить пункты ниже на свои)**
Открыть крафт улучшенной доменки

**Как оно должно было работать?**
Что должно было произойти?
Должен быть крафт примитивных кирпичей

**Скриншоты**
Скриншоты проблемы.
![image](https://user-images.githubusercontent.com/43088109/153171730-f15812b5-3688-4ecf-ba0d-19a0520014af.png)

**Модпак**
 - Версия TFG(Номер версии и ее тип(например: R2.8.8, Lite)): -
 - Версия 3.*

**Comment by SpeeeDCraft** [comment]
Исправлено
