### ISSUE TITLE
[Bug]блоки лазурита

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#84]
![unknown (1)](https://user-images.githubusercontent.com/55663835/153373585-6839efd8-4c89-43f0-be70-ed414db89bc8.png)
![unknown](https://user-images.githubusercontent.com/55663835/153373600-855a7d3a-4715-4981-b0f1-71d58315e6f2.png)
![unknown3](https://user-images.githubusercontent.com/55663835/153373604-ed0521b0-fb62-4080-91b8-7904fef4fe4e.png)

**Comment by SpeeeDCraft** [comment]
Пофикшено
