### ISSUE TITLE
Рецепты связанные с конской дробилкой нужно перенести в дробилку GT

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#87]
![2022-02-17_19 15 40](https://user-images.githubusercontent.com/55663835/154535719-c01ba03b-abd3-405d-81c8-42d33c5d6dca.png)

Сделать такие рецепты в машинах лв и выше, дабы освободить животных из рабства

**Comment by SpeeeDCraft** [comment]
Исправлено в dev, будет позже залито в основную ветку
