### ISSUE TITLE
Ошибка рецепта семян подсолнечника

### ISSUE THREAD

**Issue by Xikaro** [SpeeeDCraft/TerraFirmaGreg-1.12.2#88]
Рецепты еды некоторой требуют ванильные предметы, например вот семена делаются из 2 ванильных подсолнухов,  изменить на подсолнухи которые обрезаны ножом
![unknown](https://user-images.githubusercontent.com/55663835/154670889-0f17bb90-a393-4c5d-86a8-bd0f6b3b4361.png)

**Comment by SpeeeDCraft** [comment]
Я победил
