### ISSUE TITLE
Huge strings bug recipe

### ISSUE THREAD

**Issue by SpeeeDCraft** [SpeeeDCraft/TerraFirmaGreg-1.12.2#90]
![image](https://user-images.githubusercontent.com/52341158/156903706-80d997b4-9083-472e-9182-fa2d1850131a.png)

**Comment by Xikaro** [comment]
![Screenshot_32](https://user-images.githubusercontent.com/55663835/156940867-f62c04f3-07b3-4668-8927-f356938f360c.png)

**Comment by SpeeeDCraft** [comment]
Исправлено
